  spring:
    application:
      name: adg-rule
    profiles:
      active: prod

  logging:
    file:
      path: ./logs

  application:
    rule:
      # 需要合并的远程过滤器
      remote:
        - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt'  # AdGuard DNS filter
        - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt'  # AdAway Default Blocklist
        - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt' # CHN: AdRules DNS List
        - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt' # CHN: anti-AD

      local: []

    output:
      path: rule

      files:
        # 完整合并结果
        all.txt:
          - DOMAIN
          - REGEX
          - MODIFY
          - HOSTS

        # 给 AdGuard Home 使用的订阅
        adgh.txt:
          - DOMAIN
          - REGEX
          - HOSTS

        # 以下是分类输出，主要用于检查
        domain.txt:
          - DOMAIN

        regex.txt:
          - REGEX

        modify.txt:
          - MODIFY

        hosts.txt:
          - HOSTS
